name: appComida
description: appComida Flutter Clone.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:

    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.0
  localization: ^2.1.0
  flutter_modular: ^5.0.3
  
  flutter_triple: ^1.2.7+4
  flutter_svg_provider: ^1.0.3
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.2.19
  google_fonts: ^4.0.4


flutter_native_splash:
  color: "#FFFFFF"
  background_image: "lib/assets/images/tela_inicial.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
    
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/images/login_imagens/

  fonts:
    - family: PermanentMarker
      fonts:
       - asset: lib\assets\fonts\PermanentMarker-Regular.ttf
